/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/universities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Universities */
        get: operations["list_universities_catalog_universities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/universities/{university_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get University */
        get: operations["get_university_catalog_universities__university_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/majors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Majors */
        get: operations["list_majors_catalog_majors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_me_profile_get"];
        /** Put Profile */
        put: operations["put_profile_me_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Achievement */
        post: operations["create_achievement_me_achievements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/achievements/{achievement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Achievement */
        delete: operations["delete_achievement_me_achievements__achievement_id__delete"];
        options?: never;
        head?: never;
        /** Patch Achievement */
        patch: operations["patch_achievement_me_achievements__achievement_id__patch"];
        trace?: never;
    };
    "/me/achievements/{achievement_id}/attachments/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Link */
        post: operations["add_link_me_achievements__achievement_id__attachments_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/achievements/{achievement_id}/attachments/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Photo */
        post: operations["add_photo_me_achievements__achievement_id__attachments_photo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/achievements/{achievement_id}/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Attachment */
        delete: operations["delete_attachment_me_achievements__achievement_id__attachments__attachment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recommendations */
        get: operations["get_recommendations_me_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description Stateless what-if: never writes anything.
         */
        post: operations["preview_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/changes/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Changes */
        get: operations["latest_changes_me_changes_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/roadmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Roadmap */
        get: operations["get_roadmap_me_roadmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/roadmap/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Suggestions
         * @description What the engine recommends adding to the plan (steps already added are left out).
         */
        get: operations["get_suggestions_me_roadmap_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/roadmap/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Step */
        post: operations["add_step_me_roadmap_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/roadmap/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Step */
        delete: operations["delete_step_me_roadmap_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Patch Step */
        patch: operations["patch_step_me_roadmap_items__item_id__patch"];
        trace?: never;
    };
    "/me/roadmap.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roadmap Ics */
        get: operations["roadmap_ics_me_roadmap_ics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Favorites */
        get: operations["get_favorites_me_favorites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/favorites/{university_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Add Favorite */
        put: operations["add_favorite_me_favorites__university_id__put"];
        post?: never;
        /** Remove Favorite */
        delete: operations["remove_favorite_me_favorites__university_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/chance-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chance History */
        get: operations["get_chance_history_me_chance_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load Demo */
        post: operations["load_demo_me_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["reset_me_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/passport": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Passport */
        post: operations["passport_ai_passport_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain */
        post: operations["explain_ai_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/roadmap-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Roadmap Text
         * @description What to do and why, for suggestion ids and/or plan step ids. Titles and dates come from the engine.
         */
        post: operations["roadmap_text_ai_roadmap_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcademicRecord */
        AcademicRecord: {
            /**
             * Scale
             * @enum {string}
             */
            scale: "5" | "4" | "100" | "ib8";
            /** Value */
            value: number;
        };
        /** Achievement */
        Achievement: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "SAT" | "IELTS" | "TOEFL" | "OLYMPIAD" | "PROJECT" | "VOLUNTEER" | "COMPETITION" | "OTHER";
            /** Score */
            score?: number | null;
            /** Title */
            title?: string | null;
            /** Level */
            level?: ("school" | "city" | "national" | "international") | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "done" | "planned";
            /**
             * Attachments
             * @default []
             */
            attachments: components["schemas"]["Attachment"][];
        };
        /** AchievementCreated */
        AchievementCreated: {
            result: components["schemas"]["RecommendationResult"];
            roadmap: components["schemas"]["Roadmap"];
            diff: components["schemas"]["Diff"] | null;
            /**
             * Achievement Id
             * Format: uuid
             */
            achievement_id: string;
        };
        /** AchievementIn */
        AchievementIn: {
            /**
             * Type
             * @enum {string}
             */
            type: "SAT" | "IELTS" | "TOEFL" | "OLYMPIAD" | "PROJECT" | "VOLUNTEER" | "COMPETITION" | "OTHER";
            /** Score */
            score?: number | null;
            /** Title */
            title?: string | null;
            /** Level */
            level?: ("school" | "city" | "national" | "international") | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Status
             * @default done
             * @enum {string}
             */
            status: "done" | "planned";
        };
        /** AchievementPatch */
        AchievementPatch: {
            /** Type */
            type?: ("SAT" | "IELTS" | "TOEFL" | "OLYMPIAD" | "PROJECT" | "VOLUNTEER" | "COMPETITION" | "OTHER") | null;
            /** Score */
            score?: number | null;
            /** Title */
            title?: string | null;
            /** Level */
            level?: ("school" | "city" | "national" | "international") | null;
            /** Date */
            date?: string | null;
            /** Status */
            status?: ("done" | "planned") | null;
        };
        /** Attachment */
        Attachment: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "photo" | "link";
            /** Url */
            url?: string | null;
            /** Title */
            title?: string | null;
            /** Content Type */
            content_type?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_add_photo_me_achievements__achievement_id__attachments_photo_post */
        Body_add_photo_me_achievements__achievement_id__attachments_photo_post: {
            /** File */
            file: string;
            /** Title */
            title?: string | null;
        };
        /** ChanceChange */
        ChanceChange: {
            /** Id */
            id: string;
            /**
             * From
             * @enum {string}
             */
            from: "low" | "medium" | "high";
            /**
             * To
             * @enum {string}
             */
            to: "low" | "medium" | "high";
        };
        /** ChancePoint */
        ChancePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Chance By Uni */
            chance_by_uni: {
                [key: string]: ("low" | "medium" | "high") | null;
            };
            /** Achievement Id */
            achievement_id: string | null;
        };
        /** ComputeResponse */
        ComputeResponse: {
            result: components["schemas"]["RecommendationResult"];
            roadmap: components["schemas"]["Roadmap"];
            diff: components["schemas"]["Diff"] | null;
        };
        /** Conflict */
        Conflict: {
            /** Step Id */
            step_id: string;
            /** Message */
            message: string;
        };
        /** Deadline */
        Deadline: {
            /**
             * Type
             * @enum {string}
             */
            type: "ED" | "EA" | "REA" | "RD" | "UCAS" | "OTHER";
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** Diff */
        Diff: {
            /** Added */
            added: string[];
            /** Removed */
            removed: string[];
            /** Tier Changed */
            tier_changed: components["schemas"]["TierChange"][];
            /** Chance Changed */
            chance_changed: components["schemas"]["ChanceChange"][];
            /** Gaps Closed */
            gaps_closed: components["schemas"]["GapClosed"][];
            /** Roadmap Added */
            roadmap_added: string[];
            /** Roadmap Removed */
            roadmap_removed: string[];
            /** Cause */
            cause: string;
        };
        /** Excluded */
        Excluded: {
            /** University Id */
            university_id: string;
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
        };
        /** ExplainIn */
        ExplainIn: {
            /** University Id */
            university_id: string;
        };
        /** ExplainOut */
        ExplainOut: {
            /** University Id */
            university_id: string;
            /** Summary */
            summary: string;
            /**
             * Generated
             * @default false
             */
            generated: boolean;
        };
        /** GapClosed */
        GapClosed: {
            /** Id */
            id: string;
            /** Code */
            code: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HollandAssessment */
        HollandAssessment: {
            /**
             * Version
             * @default applyra-riasec-v1
             * @constant
             */
            version: "applyra-riasec-v1";
            /** Answers */
            answers: {
                [key: string]: number;
            };
        };
        /** LatestChanges */
        LatestChanges: {
            diff: components["schemas"]["Diff"] | null;
            /** Cause */
            cause: string | null;
            /** At */
            at: string | null;
        };
        /** LinkIn */
        LinkIn: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Title */
            title?: string | null;
        };
        /** Major */
        Major: {
            /** Id */
            id: string;
            /** Name Ru */
            name_ru: string;
            /** Name En */
            name_en: string;
            /**
             * Cip Codes
             * @default []
             */
            cip_codes: string[];
        };
        /** PassportItem */
        PassportItem: {
            /** Text */
            text: string;
            /** Profile Field */
            profile_field: string;
        };
        /** PassportOut */
        PassportOut: {
            goal: components["schemas"]["PassportItem"];
            /** Strengths */
            strengths: components["schemas"]["PassportItem"][];
            /** Constraints */
            constraints: components["schemas"]["PassportItem"][];
            risk: components["schemas"]["PassportItem"];
            /**
             * Generated
             * @default false
             */
            generated: boolean;
        };
        /** PreviewIn */
        PreviewIn: {
            profile: components["schemas"]["Profile"];
            priorities_override?: components["schemas"]["Priorities"] | null;
        };
        /** Priorities */
        Priorities: {
            /**
             * Cost
             * @default 0.5
             */
            cost: number;
            /**
             * Prestige
             * @default 0.5
             */
            prestige: number;
            /**
             * Location
             * @default 0.5
             */
            location: number;
            /**
             * Aid
             * @default 0.5
             */
            aid: number;
        };
        /** Profile */
        Profile: {
            /**
             * Grade
             * @enum {integer}
             */
            grade: 9 | 10 | 11 | 12;
            /** Gpa5 */
            gpa5?: number | null;
            academic_record?: components["schemas"]["AcademicRecord"] | null;
            holland?: components["schemas"]["HollandAssessment"] | null;
            /** Majors */
            majors: string[];
            /** Countries */
            countries: string[];
            /** Budget Per Year Usd */
            budget_per_year_usd: number;
            /** Needs Aid */
            needs_aid: boolean;
            /** Intake Year */
            intake_year: number;
            priorities: components["schemas"]["Priorities"];
            /**
             * Achievements
             * @default []
             */
            achievements: components["schemas"]["Achievement"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ProfileIn
         * @description Profile body for PUT /me/profile. Achievements are managed separately, but
         *     onboarding may send initial ones (without ids).
         */
        ProfileIn: {
            /**
             * Grade
             * @enum {integer}
             */
            grade: 9 | 10 | 11 | 12;
            /** Gpa5 */
            gpa5?: number | null;
            academic_record?: components["schemas"]["AcademicRecord"] | null;
            holland?: components["schemas"]["HollandAssessment"] | null;
            /** Majors */
            majors: string[];
            /** Countries */
            countries: string[];
            /** Budget Per Year Usd */
            budget_per_year_usd: number;
            /** Needs Aid */
            needs_aid: boolean;
            /** Intake Year */
            intake_year: number;
            priorities: components["schemas"]["Priorities"];
            /**
             * Initial Achievements
             * @default []
             */
            initial_achievements: components["schemas"]["AchievementIn"][];
        };
        /** Reason */
        Reason: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "plus" | "risk" | "blocker";
            /** Code */
            code: string;
            /** Text */
            text: string;
            /** Profile Field */
            profile_field: string;
            /** Gap */
            gap?: number | null;
        };
        /** Recommendation */
        Recommendation: {
            /** University Id */
            university_id: string;
            /**
             * Tier
             * @enum {string}
             */
            tier: "dream" | "target" | "safety";
            /**
             * Chance
             * @enum {string}
             */
            chance: "low" | "medium" | "high";
            /** Score */
            score: number;
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
        };
        /** RecommendationResult */
        RecommendationResult: {
            /** Recs */
            recs: components["schemas"]["Recommendation"][];
            /** Excluded */
            excluded: components["schemas"]["Excluded"][];
            /** Suggestions */
            suggestions: string[];
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
        };
        /** Roadmap */
        Roadmap: {
            /** Steps */
            steps: components["schemas"]["RoadmapStep"][];
            /** Conflicts */
            conflicts: components["schemas"]["Conflict"][];
            /** Next Step Id */
            next_step_id: string | null;
            /** Progress */
            progress: number;
        };
        /**
         * RoadmapStep
         * @description A step of the student's own plan (a stored roadmap item).
         */
        RoadmapStep: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "exam" | "document" | "academic" | "activity" | "application";
            /** Title */
            title: string;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /** Depends On */
            depends_on: string[];
            /** University Ids */
            university_ids: string[];
            /** Source Url */
            source_url?: string | null;
            /** Is Demo */
            is_demo: boolean;
            /** Done */
            done: boolean;
            /** Priority */
            priority: number;
            /** Source Key */
            source_key?: string | null;
            /** Note */
            note?: string | null;
        };
        /** RoadmapTextIn */
        RoadmapTextIn: {
            /** Step Ids */
            step_ids: string[];
        };
        /** RoadmapTextOut */
        RoadmapTextOut: {
            /** Items */
            items: components["schemas"]["StepText"][];
            /**
             * Generated
             * @default false
             */
            generated: boolean;
        };
        /** SatRange */
        SatRange: {
            /** P25 */
            p25: number;
            /** P50 */
            p50?: number | null;
            /** P75 */
            p75: number;
        };
        /** Sourced[Deadline] */
        Sourced_Deadline_: {
            value: components["schemas"]["Deadline"] | null;
            /** Source Url */
            source_url?: string | null;
            /** Checked At */
            checked_at?: string | null;
            /** Evidence */
            evidence?: string | null;
            /**
             * Is Demo
             * @default true
             */
            is_demo: boolean;
        };
        /** Sourced[Literal['full_need', 'partial', 'merit_only', 'none']] */
        Sourced_Literal__full_need____partial____merit_only____none___: {
            /** Value */
            value: ("full_need" | "partial" | "merit_only" | "none") | null;
            /** Source Url */
            source_url?: string | null;
            /** Checked At */
            checked_at?: string | null;
            /** Evidence */
            evidence?: string | null;
            /**
             * Is Demo
             * @default true
             */
            is_demo: boolean;
        };
        /** Sourced[SatRange] */
        Sourced_SatRange_: {
            value: components["schemas"]["SatRange"] | null;
            /** Source Url */
            source_url?: string | null;
            /** Checked At */
            checked_at?: string | null;
            /** Evidence */
            evidence?: string | null;
            /**
             * Is Demo
             * @default true
             */
            is_demo: boolean;
        };
        /** Sourced[float] */
        Sourced_float_: {
            /** Value */
            value: number | null;
            /** Source Url */
            source_url?: string | null;
            /** Checked At */
            checked_at?: string | null;
            /** Evidence */
            evidence?: string | null;
            /**
             * Is Demo
             * @default true
             */
            is_demo: boolean;
        };
        /** Sourced[int] */
        Sourced_int_: {
            /** Value */
            value: number | null;
            /** Source Url */
            source_url?: string | null;
            /** Checked At */
            checked_at?: string | null;
            /** Evidence */
            evidence?: string | null;
            /**
             * Is Demo
             * @default true
             */
            is_demo: boolean;
        };
        /**
         * StepIn
         * @description Add a step: from a suggestion (fields optional overrides) or a custom one (title, kind, due_date required).
         */
        StepIn: {
            /** Suggestion Id */
            suggestion_id?: string | null;
            /** Title */
            title?: string | null;
            /** Kind */
            kind?: ("exam" | "document" | "academic" | "activity" | "application") | null;
            /** Due Date */
            due_date?: string | null;
            /** Note */
            note?: string | null;
        };
        /** StepPatch */
        StepPatch: {
            /** Done */
            done?: boolean | null;
            /** Title */
            title?: string | null;
            /** Kind */
            kind?: ("exam" | "document" | "academic" | "activity" | "application") | null;
            /** Due Date */
            due_date?: string | null;
            /** Note */
            note?: string | null;
        };
        /** StepText */
        StepText: {
            /** Id */
            id: string;
            /** Description */
            description: string;
        };
        /**
         * Suggestion
         * @description What the engine recommends adding to the plan. Deterministic; never saved until the student adds it.
         */
        Suggestion: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "exam" | "document" | "academic" | "activity" | "application";
            /** Title */
            title: string;
            why: components["schemas"]["SuggestionWhy"];
            /** Description */
            description: string;
            /**
             * Suggested Due
             * Format: date
             */
            suggested_due: string;
            /** University Ids */
            university_ids: string[];
            /** Source Url */
            source_url?: string | null;
            /** Is Demo */
            is_demo: boolean;
            /** Priority */
            priority: number;
        };
        /** SuggestionWhy */
        SuggestionWhy: {
            /** Text */
            text: string;
            /** Profile Field */
            profile_field: string;
        };
        /** TierChange */
        TierChange: {
            /** Id */
            id: string;
            /**
             * From
             * @enum {string}
             */
            from: "dream" | "target" | "safety";
            /**
             * To
             * @enum {string}
             */
            to: "dream" | "target" | "safety";
        };
        /** University */
        University: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Country */
            country: string;
            /** City */
            city: string;
            /** Website */
            website: string;
            /** Majors */
            majors: string[];
            acceptance_rate: components["schemas"]["Sourced_float_"];
            sat: components["schemas"]["Sourced_SatRange_"];
            gpa_avg: components["schemas"]["Sourced_float_"];
            ielts_min: components["schemas"]["Sourced_float_"];
            cost_per_year_usd: components["schemas"]["Sourced_int_"];
            intl_aid: components["schemas"]["Sourced_Literal__full_need____partial____merit_only____none___"];
            /** Deadlines */
            deadlines: components["schemas"]["Sourced_Deadline_"][];
            /**
             * Extra Requirements
             * @default []
             */
            extra_requirements: string[];
            /**
             * Documents
             * @default []
             */
            documents: string[];
            /** World Rank */
            world_rank: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_universities_catalog_universities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["University"][];
                };
            };
        };
    };
    get_university_catalog_universities__university_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                university_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["University"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_majors_catalog_majors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Major"][];
                };
            };
        };
    };
    get_profile_me_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_profile_me_profile_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_achievement_me_achievements_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AchievementIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_achievement_me_achievements__achievement_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                achievement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_achievement_me_achievements__achievement_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                achievement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AchievementPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_link_me_achievements__achievement_id__attachments_link_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                achievement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_photo_me_achievements__achievement_id__attachments_photo_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                achievement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_photo_me_achievements__achievement_id__attachments_photo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_attachment_me_achievements__achievement_id__attachments__attachment_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                achievement_id: string;
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendations_me_recommendations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_changes_me_changes_latest_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestChanges"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_roadmap_me_roadmap_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roadmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_suggestions_me_roadmap_suggestions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_step_me_roadmap_items_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roadmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_step_me_roadmap_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roadmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_step_me_roadmap_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roadmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roadmap_ics_me_roadmap_ics_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_favorites_me_favorites_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_favorite_me_favorites__university_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                university_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_favorite_me_favorites__university_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                university_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chance_history_me_chance_history_get: {
        parameters: {
            query?: {
                /** @description comma-separated university ids */
                ids?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChancePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_demo_me_demo_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_me_reset_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    passport_ai_passport_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_ai_explain_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roadmap_text_ai_roadmap_text_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoadmapTextIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapTextOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
