"""Builds universities.json / majors.json from a compact table.

The table holds approximate demo figures (is_demo=true). US rows are then overwritten with real data by
pipeline/scorecard.py + cds.py + verify.py --merge; this script keeps any row that already has verified facts.
Unknown values are None. world_rank: QS World University Rankings 2025 (approximate); 1000 = not in the ranking.
Run: python supabase/seed/build_seed.py
"""
import json
from pathlib import Path

HERE = Path(__file__).parent

MAJORS = [
    ("cs", "Компьютерные науки", "Computer Science", ["11.0701"]),
    ("engineering", "Инженерия", "Engineering", ["14.0101"]),
    ("economics", "Экономика", "Economics", ["45.0601"]),
    ("business", "Бизнес и менеджмент", "Business & Management", ["52.0201"]),
    ("math", "Математика", "Mathematics", ["27.0101"]),
    ("physics", "Физика", "Physics", ["40.0801"]),
    ("biology", "Биология", "Biology", ["26.0101"]),
    ("medicine", "Медицина", "Medicine", ["51.1201"]),
    ("design", "Дизайн и архитектура", "Design & Architecture", ["50.0401", "04.0201"]),
    ("social_sciences", "Социальные науки и международные отношения", "Social Sciences & IR", ["45.0901", "45.1001"]),
]

US_DOCS = ["transcript", "essay", "recommendations", "financial_docs", "passport"]
UK_DOCS = ["transcript", "personal_statement", "recommendations", "passport"]
EU_DOCS = ["transcript", "motivation_letter", "cv", "passport"]
ASIA_DOCS = ["transcript", "motivation_letter", "recommendations", "passport"]

# id, name, country, city, website, majors, rate, (sat p25, p75) | None, gpa_avg, ielts_min, cost, aid,
# deadlines [(type, date)], extra_requirements, documents, world_rank
ROWS = [
    # --- United States -------------------------------------------------------
    ("mit", "Massachusetts Institute of Technology", "US", "Cambridge, MA", "https://mitadmissions.org",
     ["cs", "engineering", "math", "physics", "economics", "biology"], 0.045, (1520, 1580), None, 7.0, 86000, "full_need",
     [("EA", "2026-11-01"), ("RD", "2027-01-05")], [], US_DOCS, 1),
    ("harvard", "Harvard University", "US", "Cambridge, MA", "https://college.harvard.edu/admissions",
     ["cs", "economics", "math", "physics", "biology", "social_sciences"], 0.035, (1500, 1580), None, None, 87000, "full_need",
     [("REA", "2026-11-01"), ("RD", "2027-01-01")], ["Интервью с выпускником (по возможности)"], US_DOCS, 4),
    ("stanford", "Stanford University", "US", "Stanford, CA", "https://admission.stanford.edu",
     ["cs", "engineering", "economics", "math", "physics", "biology", "design"], 0.037, (1500, 1580), None, None, 89000, "full_need",
     [("REA", "2026-11-01"), ("RD", "2027-01-05")], [], US_DOCS, 6),
    ("princeton", "Princeton University", "US", "Princeton, NJ", "https://admission.princeton.edu",
     ["cs", "engineering", "economics", "math", "physics"], 0.045, (1510, 1580), 3.9, None, 83000, "full_need",
     [("REA", "2026-11-01"), ("RD", "2027-01-01")], [], US_DOCS, 22),
    ("yale", "Yale University", "US", "New Haven, CT", "https://admissions.yale.edu",
     ["cs", "economics", "math", "physics", "biology", "social_sciences"], 0.046, (1500, 1580), None, None, 88000, "full_need",
     [("REA", "2026-11-01"), ("RD", "2027-01-02")], [], US_DOCS, 23),
    ("upenn", "University of Pennsylvania", "US", "Philadelphia, PA", "https://admissions.upenn.edu",
     ["business", "economics", "cs", "engineering", "biology"], 0.059, (1500, 1570), 3.9, 7.0, 90000, "partial",
     [("ED", "2026-11-01"), ("RD", "2027-01-05")], [], US_DOCS, 11),
    ("columbia", "Columbia University", "US", "New York, NY", "https://undergrad.admissions.columbia.edu",
     ["cs", "engineering", "economics", "math", "social_sciences"], 0.039, (1500, 1570), None, None, 91000, "full_need",
     [("ED", "2026-11-01"), ("RD", "2027-01-01")], [], US_DOCS, 34),
    ("cornell", "Cornell University", "US", "Ithaca, NY", "https://admissions.cornell.edu",
     ["cs", "engineering", "business", "economics", "biology", "design"], 0.079, (1480, 1560), None, 7.0, 90000, "partial",
     [("ED", "2026-11-01"), ("RD", "2027-01-02")], [], US_DOCS, 16),
    ("uchicago", "University of Chicago", "US", "Chicago, IL", "https://collegeadmissions.uchicago.edu",
     ["economics", "math", "physics", "cs", "biology", "social_sciences"], 0.05, (1510, 1580), None, 7.0, 93000, "partial",
     [("ED", "2026-11-01"), ("EA", "2026-11-01"), ("RD", "2027-01-06")], [], US_DOCS, 21),
    ("nyu", "New York University", "US", "New York, NY", "https://www.nyu.edu/admissions",
     ["business", "economics", "cs", "design", "social_sciences"], 0.08, (1470, 1570), None, 7.5, 92000, "partial",
     [("ED", "2026-11-01"), ("RD", "2027-01-05")], [], US_DOCS, 43),
    ("umich", "University of Michigan", "US", "Ann Arbor, MI", "https://admissions.umich.edu",
     ["cs", "engineering", "business", "economics", "math", "biology"], 0.18, (1460, 1560), 3.9, 6.5, 83000, "merit_only",
     [("EA", "2026-11-01"), ("RD", "2027-02-01")], [], US_DOCS, 44),
    ("ucla", "University of California, Los Angeles", "US", "Los Angeles, CA", "https://admission.ucla.edu",
     ["cs", "engineering", "economics", "biology", "design", "social_sciences"], 0.09, None, 3.9, 7.0, 72000, "none",
     [("OTHER", "2026-11-30")], ["Personal Insight Questions (4 ответа)"], ["transcript", "essay", "passport"], 42),
    ("gatech", "Georgia Institute of Technology", "US", "Atlanta, GA", "https://admission.gatech.edu",
     ["cs", "engineering", "math", "physics", "business"], 0.17, (1370, 1530), None, 6.5, 55000, "none",
     [("EA", "2026-10-15"), ("RD", "2027-01-06")], [], US_DOCS, 114),
    ("boston_u", "Boston University", "US", "Boston, MA", "https://www.bu.edu/admissions",
     ["cs", "engineering", "business", "economics", "biology", "social_sciences"], 0.11, (1420, 1540), 3.9, 7.0, 88000, "merit_only",
     [("ED", "2026-11-01"), ("RD", "2027-01-04")], [], US_DOCS, 108),
    ("uiuc", "University of Illinois Urbana-Champaign", "US", "Champaign, IL", "https://www.admissions.illinois.edu",
     ["cs", "engineering", "business", "economics", "math", "physics"], 0.44, (1350, 1530), 3.8, 6.5, 62000, "merit_only",
     [("EA", "2026-11-01"), ("RD", "2027-01-05")], [], US_DOCS, 69),
    ("purdue", "Purdue University", "US", "West Lafayette, IN", "https://admissions.purdue.edu",
     ["engineering", "cs", "business", "math", "physics", "biology", "economics"], 0.53, (1190, 1450), 3.7, 6.5, 46000, "none",
     [("EA", "2026-11-01"), ("RD", "2027-01-15")], [], US_DOCS, 89),
    ("penn_state", "Pennsylvania State University", "US", "University Park, PA", "https://admissions.psu.edu",
     ["engineering", "business", "cs", "economics", "biology"], 0.55, (1160, 1370), 3.6, 6.5, 55000, "none",
     [("EA", "2026-11-01"), ("RD", "2026-11-30")], [], US_DOCS, 83),
    ("umn", "University of Minnesota Twin Cities", "US", "Minneapolis, MN", "https://admissions.tc.umn.edu",
     ["engineering", "cs", "business", "economics", "biology", "math"], 0.75, (1230, 1440), 3.7, 6.5, 52000, "merit_only",
     [("EA", "2026-11-01"), ("RD", "2027-01-01")], [], US_DOCS, 185),
    ("asu", "Arizona State University", "US", "Tempe, AZ", "https://admission.asu.edu",
     ["cs", "engineering", "business", "design", "biology", "social_sciences"], 0.90, (1100, 1360), 3.5, 6.0, 48000, "merit_only",
     [("RD", "2027-02-01")], [], ["transcript", "passport", "financial_docs"], 179),
    # --- United Kingdom ------------------------------------------------------
    ("oxford", "University of Oxford", "UK", "Oxford", "https://www.ox.ac.uk/admissions/undergraduate",
     ["cs", "engineering", "economics", "math", "physics", "biology", "medicine"], 0.14, None, None, 7.5, 72000, "merit_only",
     [("UCAS", "2026-10-15")], ["A-levels / IB или Foundation year", "Вступительный тест и интервью"], UK_DOCS, 3),
    ("cambridge", "University of Cambridge", "UK", "Cambridge", "https://www.undergraduate.study.cam.ac.uk",
     ["cs", "engineering", "economics", "math", "physics", "biology", "medicine", "design"], 0.18, None, None, 7.5, 75000, "merit_only",
     [("UCAS", "2026-10-15")], ["A-levels / IB или Foundation year", "Интервью"], UK_DOCS, 5),
    ("imperial", "Imperial College London", "UK", "London", "https://www.imperial.ac.uk/study/apply/undergraduate",
     ["cs", "engineering", "math", "physics", "biology", "medicine", "economics"], 0.14, None, None, 7.0, 70000, "merit_only",
     [("UCAS", "2027-01-14")], ["A-levels / IB или Foundation year"], UK_DOCS, 2),
    ("ucl", "University College London", "UK", "London", "https://www.ucl.ac.uk/prospective-students/undergraduate",
     ["cs", "engineering", "economics", "math", "physics", "biology", "design", "social_sciences"], 0.30, None, None, 7.0, 62000, "merit_only",
     [("UCAS", "2027-01-14")], ["A-levels / IB или Foundation year"], UK_DOCS, 9),
    ("lse", "London School of Economics", "UK", "London", "https://www.lse.ac.uk/study-at-lse/undergraduate",
     ["economics", "business", "math", "social_sciences"], 0.09, None, None, 7.0, 60000, "partial",
     [("UCAS", "2027-01-14")], ["A-levels / IB или Foundation year"], UK_DOCS, 50),
    ("edinburgh", "University of Edinburgh", "UK", "Edinburgh", "https://www.ed.ac.uk/studying/undergraduate",
     ["cs", "engineering", "economics", "business", "math", "physics", "biology", "design", "social_sciences"], 0.40, None, None, 6.5, 50000, "merit_only",
     [("UCAS", "2027-01-14")], [], UK_DOCS, 27),
    ("manchester", "University of Manchester", "UK", "Manchester", "https://www.manchester.ac.uk/study/undergraduate",
     ["cs", "engineering", "economics", "business", "math", "physics", "biology", "social_sciences"], 0.55, None, None, 6.5, 45000, "merit_only",
     [("UCAS", "2027-01-14")], [], UK_DOCS, 34),
    ("kcl", "King's College London", "UK", "London", "https://www.kcl.ac.uk/study/undergraduate",
     ["economics", "business", "cs", "biology", "medicine", "social_sciences"], 0.38, None, None, 7.0, 58000, "merit_only",
     [("UCAS", "2027-01-14")], [], UK_DOCS, 40),
    ("warwick", "University of Warwick", "UK", "Coventry", "https://warwick.ac.uk/study/undergraduate",
     ["cs", "economics", "business", "math", "physics", "engineering"], 0.30, None, None, 6.5, 52000, "merit_only",
     [("UCAS", "2027-01-14")], [], UK_DOCS, 69),
    ("leeds", "University of Leeds", "UK", "Leeds", "https://www.leeds.ac.uk/undergraduate",
     ["cs", "engineering", "economics", "business", "biology", "design", "social_sciences"], 0.70, None, None, 6.5, 42000, "merit_only",
     [("UCAS", "2027-01-14")], ["Foundation year для аттестата РК"], UK_DOCS, 82),
    # --- Netherlands ---------------------------------------------------------
    ("tudelft", "Delft University of Technology", "NL", "Delft", "https://www.tudelft.nl/en/education/admission-and-application",
     ["engineering", "cs", "math", "physics", "design"], None, None, None, 6.5, 32000, "merit_only",
     [("OTHER", "2027-01-15")], ["Отбор numerus fixus на части программ"], EU_DOCS, 49),
    ("uva", "University of Amsterdam", "NL", "Amsterdam", "https://www.uva.nl/en/education/bachelor-s",
     ["economics", "business", "cs", "social_sciences", "biology"], None, None, None, 6.5, 30000, "merit_only",
     [("OTHER", "2027-05-01")], [], EU_DOCS, 53),
    ("erasmus", "Erasmus University Rotterdam", "NL", "Rotterdam", "https://www.eur.nl/en/education/bachelor",
     ["economics", "business"], None, None, None, 6.5, 28000, "merit_only",
     [("OTHER", "2027-01-15")], [], EU_DOCS, 176),
    ("maastricht", "Maastricht University", "NL", "Maastricht", "https://www.maastrichtuniversity.nl/education/bachelor",
     ["economics", "business", "social_sciences", "medicine"], None, None, None, 6.5, 26000, "merit_only",
     [("OTHER", "2027-05-01")], [], EU_DOCS, 239),
    # --- Germany -------------------------------------------------------------
    ("tum", "Technical University of Munich", "DE", "Munich", "https://www.tum.de/en/studies/application",
     ["engineering", "cs", "math", "physics", "business"], None, None, None, 6.5, 24000, "none",
     [("OTHER", "2027-07-15")], ["Studienkolleg или 1 год вуза в РК для аттестата"], EU_DOCS, 28),
    ("rwth", "RWTH Aachen University", "DE", "Aachen", "https://www.rwth-aachen.de/go/id/bkvx/?lidx=1",
     ["engineering", "cs", "math", "physics", "business"], None, None, None, 6.5, 14000, "none",
     [("OTHER", "2027-07-15")], ["Studienkolleg или 1 год вуза в РК для аттестата", "Немецкий язык для программ на немецком"], EU_DOCS, 99),
    ("lmu", "LMU Munich", "DE", "Munich", "https://www.lmu.de/en/study/all-degrees-and-programs/application-and-admission",
     ["economics", "business", "physics", "math", "biology", "medicine", "social_sciences"], None, None, None, 6.5, 15000, "none",
     [("OTHER", "2027-07-15")], ["Studienkolleg или 1 год вуза в РК для аттестата", "Немецкий язык для программ на немецком"], EU_DOCS, 59),
    # --- South Korea ---------------------------------------------------------
    ("kaist", "KAIST", "KR", "Daejeon", "https://admission.kaist.ac.kr/intl-undergraduate",
     ["engineering", "cs", "math", "physics", "biology", "business"], None, None, None, 6.5, 12000, "merit_only",
     [("OTHER", "2026-12-04")], [], ASIA_DOCS, 53),
    ("snu", "Seoul National University", "KR", "Seoul", "https://admission.snu.ac.kr/undergraduate/international",
     ["engineering", "cs", "economics", "business", "math", "physics", "biology", "social_sciences"], None, None, None, 6.5, 15000, "merit_only",
     [("OTHER", "2026-10-01")], [], ASIA_DOCS, 31),
    ("yonsei", "Yonsei University (Underwood International College)", "KR", "Seoul", "https://uic.yonsei.ac.kr/main/admission.php",
     ["economics", "business", "social_sciences", "cs", "engineering", "design", "biology"], None, None, None, 6.5, 20000, "merit_only",
     [("OTHER", "2027-01-10")], [], ASIA_DOCS, 56),
    # --- Singapore -----------------------------------------------------------
    ("nus", "National University of Singapore", "SG", "Singapore", "https://www.nus.edu.sg/oam",
     ["cs", "engineering", "economics", "business", "math", "physics", "biology", "design"], None, None, None, 6.5, 40000, "partial",
     [("OTHER", "2027-02-20")], ["Вступительные тесты/интервью на части программ"], ASIA_DOCS, 8),
    ("ntu", "Nanyang Technological University", "SG", "Singapore", "https://www.ntu.edu.sg/admissions/undergraduate",
     ["cs", "engineering", "business", "math", "physics", "biology", "design"], None, None, None, 6.5, 38000, "partial",
     [("OTHER", "2027-02-15")], [], ASIA_DOCS, 15),
    ("smu", "Singapore Management University", "SG", "Singapore", "https://admissions.smu.edu.sg",
     ["business", "economics", "cs", "social_sciences"], None, None, None, 6.5, 38000, "partial",
     [("OTHER", "2027-02-15")], ["Интервью или оценочное задание на части программ"], ASIA_DOCS, 500),
    # --- Canada --------------------------------------------------------------
    ("utoronto", "University of Toronto", "CA", "Toronto", "https://future.utoronto.ca",
     ["cs", "engineering", "economics", "business", "math", "physics", "biology", "social_sciences"], 0.43, None, None, 6.5, 58000, "merit_only",
     [("OTHER", "2027-01-15")], [], ASIA_DOCS[:1] + ["cv", "passport"], 25),
    ("ubc", "University of British Columbia", "CA", "Vancouver", "https://you.ubc.ca",
     ["cs", "engineering", "economics", "business", "math", "physics", "biology", "design"], 0.52, None, None, 6.5, 55000, "merit_only",
     [("OTHER", "2027-01-15")], [], ["transcript", "essay", "passport"], 38),
    ("mcgill", "McGill University", "CA", "Montreal", "https://www.mcgill.ca/undergraduate-admissions",
     ["cs", "engineering", "economics", "business", "math", "physics", "biology", "social_sciences"], 0.40, None, None, 6.5, 50000, "merit_only",
     [("OTHER", "2027-01-15")], [], ["transcript", "passport"], 29),
    ("waterloo", "University of Waterloo", "CA", "Waterloo", "https://uwaterloo.ca/future-students",
     ["cs", "engineering", "math", "physics", "business"], 0.53, None, None, 6.5, 50000, "merit_only",
     [("OTHER", "2027-02-01")], ["Admission Information Form"], ["transcript", "cv", "passport"], 115),
    # --- Hong Kong -----------------------------------------------------------
    ("hku", "The University of Hong Kong", "HK", "Hong Kong", "https://admissions.hku.hk",
     ["cs", "engineering", "economics", "business", "medicine", "social_sciences", "biology"], None, None, None, 6.5, 36000, "merit_only",
     [("OTHER", "2027-01-06")], [], ASIA_DOCS, 17),
    ("hkust", "Hong Kong University of Science and Technology", "HK", "Hong Kong", "https://join.hkust.edu.hk",
     ["cs", "engineering", "business", "economics", "math", "physics"], None, None, None, 6.5, 34000, "merit_only",
     [("OTHER", "2027-01-05")], [], ASIA_DOCS, 47),
    ("cuhk", "The Chinese University of Hong Kong", "HK", "Hong Kong", "https://admission.cuhk.edu.hk",
     ["cs", "engineering", "business", "economics", "medicine", "biology", "social_sciences"], None, None, None, 6.0, 34000, "merit_only",
     [("OTHER", "2027-01-05")], [], ASIA_DOCS, 36),
    # --- China ---------------------------------------------------------------
    ("tsinghua", "Tsinghua University", "CN", "Beijing", "https://join-tsinghua.edu.cn/en",
     ["engineering", "cs", "math", "physics", "economics", "business", "design"], None, None, None, None, 11000, "partial",
     [("OTHER", "2026-12-15")], ["HSK 5–6 для программ на китайском языке", "Вступительный экзамен или интервью"], ASIA_DOCS, 20),
    ("pku", "Peking University", "CN", "Beijing", "https://www.isd.pku.edu.cn",
     ["cs", "economics", "math", "physics", "biology", "medicine", "social_sciences"], None, None, None, None, 11000, "partial",
     [("OTHER", "2027-01-05")], ["HSK 5–6 для программ на китайском языке", "Вступительный экзамен или интервью"], ASIA_DOCS, 14),
    ("fudan", "Fudan University", "CN", "Shanghai", "https://iso.fudan.edu.cn",
     ["economics", "business", "medicine", "social_sciences", "cs", "math"], None, None, None, None, 11000, "partial",
     [("OTHER", "2027-02-28")], ["HSK 5–6 для программ на китайском языке", "Вступительный экзамен или интервью"], ASIA_DOCS, 39),
    # --- Italy ---------------------------------------------------------------
    ("bocconi", "Bocconi University", "IT", "Milan", "https://www.unibocconi.eu/en/programs/bachelor-degree-programs",
     ["economics", "business", "social_sciences", "cs", "math"], None, None, None, 6.5, 30000, "partial",
     [("OTHER", "2027-02-18")], ["Онлайн-тест Bocconi или SAT"], EU_DOCS, 300),
    ("polimi", "Politecnico di Milano", "IT", "Milan", "https://www.polimi.it/en/international-prospective-students",
     ["engineering", "design", "cs", "math", "physics"], None, None, None, 6.0, 17000, "partial",
     [("OTHER", "2027-02-28")], ["Вступительный тест TOL/TIL (или SAT)"], EU_DOCS, 111),
    ("unibo", "University of Bologna", "IT", "Bologna", "https://www.unibo.it/en/study/international-students",
     ["economics", "business", "engineering", "medicine", "social_sciences", "biology"], None, None, None, 6.0, 14000, "partial",
     [("OTHER", "2027-03-31")], [], EU_DOCS, 138),
    # --- Japan ---------------------------------------------------------------
    ("utokyo", "The University of Tokyo (PEAK)", "JP", "Tokyo", "https://peak.c.u-tokyo.ac.jp",
     ["engineering", "cs", "physics", "math", "biology", "social_sciences"], None, None, None, 6.5, 16000, "merit_only",
     [("OTHER", "2026-12-05")], ["Англоязычная программа PEAK; интервью для финалистов"], ASIA_DOCS, 32),
    ("kyoto", "Kyoto University (iUP)", "JP", "Kyoto", "https://iup.kyoto-u.ac.jp",
     ["engineering", "cs", "economics", "physics", "math", "biology"], None, None, None, 6.0, 15000, "merit_only",
     [("OTHER", "2026-11-20")], ["Подготовительный японский в первый год (iUP)", "Интервью"], ASIA_DOCS, 50),
    ("waseda", "Waseda University (SILS)", "JP", "Tokyo", "https://www.waseda.jp/inst/admission/en/undergraduate",
     ["economics", "business", "social_sciences", "cs", "engineering"], None, None, None, 6.0, 20000, "merit_only",
     [("OTHER", "2026-12-01")], [], ASIA_DOCS, 181),
    # --- Switzerland ---------------------------------------------------------
    ("ethz", "ETH Zurich", "CH", "Zurich", "https://ethz.ch/en/studies/registration-application/bachelor.html",
     ["engineering", "cs", "math", "physics", "biology", "design"], None, None, None, None, 28000, "none",
     [("OTHER", "2027-04-30")], ["Бакалавриат на немецком (уровень C1)", "Вступительный экзамен ETH для аттестата РК"], EU_DOCS, 7),
    ("epfl", "EPFL", "CH", "Lausanne", "https://www.epfl.ch/education/admission/admission-2",
     ["engineering", "cs", "math", "physics", "biology", "design"], None, None, None, None, 26000, "none",
     [("OTHER", "2027-04-30")], ["Бакалавриат на французском (уровень B2)", "Вступительный экзамен или подготовительный курс CMS"], EU_DOCS, 26),
    ("uzh", "University of Zurich", "CH", "Zurich", "https://www.uzh.ch/en/studies/application/bachelor.html",
     ["economics", "business", "cs", "biology", "medicine", "social_sciences"], None, None, None, None, 27000, "none",
     [("OTHER", "2027-04-30")], ["Бакалавриат на немецком (уровень C1)", "Экзамен ECUS для аттестата РК"], EU_DOCS, 107),
    # --- France --------------------------------------------------------------
    ("polytechnique", "École Polytechnique (Bachelor)", "FR", "Palaiseau", "https://programmes.polytechnique.edu/en/bachelor-program",
     ["math", "physics", "cs", "economics", "engineering"], None, None, None, 6.5, 35000, "partial",
     [("OTHER", "2027-01-10")], ["Письменный тест и интервью"], EU_DOCS, 46),
    ("sciencespo", "Sciences Po", "FR", "Paris", "https://www.sciencespo.fr/admissions/en",
     ["social_sciences", "economics", "business"], None, None, None, 7.0, 30000, "partial",
     [("OTHER", "2027-02-05")], ["Интервью"], EU_DOCS, 244),
    ("sorbonne", "Sorbonne University", "FR", "Paris", "https://www.sorbonne-universite.fr/en/admissions",
     ["physics", "math", "biology", "medicine", "cs", "engineering"], None, None, None, None, 16000, "none",
     [("OTHER", "2026-12-15")], ["Французский язык B2 (DELF/TCF)", "Заявка через Études en France"], EU_DOCS, 63),
    # --- Australia -----------------------------------------------------------
    ("unimelb", "The University of Melbourne", "AU", "Melbourne", "https://study.unimelb.edu.au/how-to-apply",
     ["cs", "engineering", "economics", "business", "biology", "design", "social_sciences"], None, None, None, 6.5, 52000, "merit_only",
     [("OTHER", "2026-11-30")], ["Foundation year для аттестата РК"], UK_DOCS, 13),
    ("usyd", "The University of Sydney", "AU", "Sydney", "https://www.sydney.edu.au/study/applying.html",
     ["cs", "engineering", "economics", "business", "medicine", "biology", "design"], None, None, None, 6.5, 53000, "merit_only",
     [("OTHER", "2026-11-30")], ["Foundation year для аттестата РК"], UK_DOCS, 18),
    ("unsw", "UNSW Sydney", "AU", "Sydney", "https://www.unsw.edu.au/study/how-to-apply",
     ["engineering", "cs", "business", "economics", "math", "physics", "design"], None, None, None, 6.5, 50000, "merit_only",
     [("OTHER", "2026-11-30")], ["Foundation year для аттестата РК"], UK_DOCS, 19),
    ("anu", "Australian National University", "AU", "Canberra", "https://study.anu.edu.au/apply",
     ["economics", "social_sciences", "cs", "physics", "math", "biology"], None, None, None, 6.5, 48000, "merit_only",
     [("OTHER", "2026-11-30")], ["Foundation year для аттестата РК"], UK_DOCS, 30),
    # --- Ireland -------------------------------------------------------------
    ("tcd", "Trinity College Dublin", "IE", "Dublin", "https://www.tcd.ie/study/non-eu/undergraduate",
     ["cs", "engineering", "economics", "business", "math", "physics", "biology", "medicine", "social_sciences"], None, None, None, 6.5, 45000, "merit_only",
     [("OTHER", "2027-02-01")], ["Foundation year или 1 год вуза в РК для аттестата"], UK_DOCS, 87),
    ("ucd", "University College Dublin", "IE", "Dublin", "https://www.ucd.ie/global/study-at-ucd",
     ["business", "economics", "cs", "engineering", "medicine", "biology", "design"], None, None, None, 6.5, 42000, "merit_only",
     [("OTHER", "2027-05-01")], ["Foundation year или 1 год вуза в РК для аттестата"], UK_DOCS, 126),
    ("galway", "University of Galway", "IE", "Galway", "https://www.universityofgalway.ie/international-students",
     ["business", "engineering", "cs", "biology", "medicine", "social_sciences"], None, None, None, 6.5, 36000, "merit_only",
     [("OTHER", "2027-06-30")], ["Foundation year или 1 год вуза в РК для аттестата"], UK_DOCS, 273),
    # --- Sweden --------------------------------------------------------------
    ("kth", "KTH Royal Institute of Technology", "SE", "Stockholm", "https://www.kth.se/en/studies/bachelor",
     ["engineering", "cs", "math", "physics", "design"], None, None, None, 6.5, 30000, "merit_only",
     [("OTHER", "2027-02-01")], ["Мало англоязычных бакалаврских программ", "1 год вуза в РК для аттестата"], EU_DOCS, 74),
    ("lund", "Lund University", "SE", "Lund", "https://www.lunduniversity.lu.se/admissions/bachelors-masters-studies",
     ["business", "economics", "social_sciences", "physics", "biology", "engineering"], None, None, None, 6.5, 28000, "merit_only",
     [("OTHER", "2027-02-01")], ["Мало англоязычных бакалаврских программ", "1 год вуза в РК для аттестата"], EU_DOCS, 72),
    ("uppsala", "Uppsala University", "SE", "Uppsala", "https://www.uu.se/en/study/bachelors-programmes",
     ["physics", "biology", "social_sciences", "economics", "math", "cs"], None, None, None, 6.5, 26000, "merit_only",
     [("OTHER", "2027-02-01")], ["Мало англоязычных бакалаврских программ", "1 год вуза в РК для аттестата"], EU_DOCS, 103),
    # --- Spain ---------------------------------------------------------------
    ("ie_university", "IE University", "ES", "Madrid / Segovia", "https://www.ie.edu/university/admissions",
     ["business", "economics", "cs", "design", "social_sciences"], None, None, None, 6.5, 40000, "partial",
     [("OTHER", "2027-03-01")], ["Собственный вступительный тест IE или SAT", "Интервью"], EU_DOCS, 500),
    ("uc3m", "Universidad Carlos III de Madrid", "ES", "Madrid", "https://www.uc3m.es/bachelor-degree/admission",
     ["economics", "business", "engineering", "cs", "math", "social_sciences"], None, None, None, 6.5, 22000, "none",
     [("OTHER", "2027-04-30")], ["Омологация аттестата (credencial UNEDasiss)"], EU_DOCS, 300),
    ("ub", "University of Barcelona", "ES", "Barcelona", "https://www.ub.edu/web/portal/en/studies/bachelors-degrees",
     ["medicine", "biology", "economics", "business", "physics", "math", "social_sciences"], None, None, None, None, 16000, "none",
     [("OTHER", "2027-06-30")], ["Обучение на испанском/каталанском (B2)", "Омологация аттестата (credencial UNEDasiss)"], EU_DOCS, 165),
]

UNRANKED = 1000  # not in the QS World University Rankings; the UI says so instead of showing a number
DE_LANG = "Обучение на немецком (DSH-2 / TestDaF 4) для большинства программ"
DE_SCHOOL = "Studienkolleg или 1 год вуза в РК для аттестата"
FR_LANG = "Обучение на французском (B2), подача через Études en France"
ES_HOMOLOG = "Омологация аттестата (credencial UNEDasiss)"
CN_LANG = "HSK 4–5 для программ на китайском языке"
FOUNDATION = "Foundation year для аттестата РК"


def row(uid, name, country, city, site, majors, ielts, cost, aid, deadlines, extra, docs, rank):
    """Non-US row: acceptance rate, SAT and GPA are not published by these universities."""
    deadlines = [("OTHER", deadlines)] if isinstance(deadlines, str) else deadlines
    return (uid, name, country, city, site, majors, None, None, None, ielts, cost, aid, deadlines, extra, docs, rank)


# Added 2026-09-19: at least 10 universities per country where 10 relevant options exist.
ROWS += [
    # --- Netherlands ---------------------------------------------------------
    row("utrecht", "Utrecht University", "NL", "Utrecht", "https://www.uu.nl/en/bachelors",
        ["economics", "social_sciences", "biology", "cs", "math", "physics"], 6.5, 30000, "merit_only", "2027-05-01", [], EU_DOCS, 107),
    row("leiden", "Leiden University", "NL", "Leiden / The Hague", "https://www.universiteitleiden.nl/en/education/admission-and-application",
        ["social_sciences", "economics", "cs", "biology", "physics", "math"], 6.5, 30000, "merit_only", "2027-05-01", [], EU_DOCS, 126),
    row("groningen", "University of Groningen", "NL", "Groningen", "https://www.rug.nl/bachelors",
        ["economics", "business", "cs", "engineering", "math", "physics", "biology", "social_sciences"], 6.5, 27000, "merit_only", "2027-05-01", [], EU_DOCS, 147),
    row("tue", "Eindhoven University of Technology", "NL", "Eindhoven", "https://www.tue.nl/en/education/become-a-tue-student",
        ["engineering", "cs", "math", "physics", "design"], 6.5, 30000, "merit_only", "2027-04-01", [], EU_DOCS, 124),
    row("vu_amsterdam", "Vrije Universiteit Amsterdam", "NL", "Amsterdam", "https://vu.nl/en/education/bachelor",
        ["economics", "business", "cs", "social_sciences", "biology", "math"], 6.5, 29000, "merit_only", "2027-04-01", [], EU_DOCS, 213),
    row("tilburg", "Tilburg University", "NL", "Tilburg", "https://www.tilburguniversity.edu/education/bachelors-programs",
        ["economics", "business", "social_sciences", "cs"], 6.5, 26000, "merit_only", "2027-05-01", [], EU_DOCS, 361),
    # --- Germany -------------------------------------------------------------
    row("heidelberg", "Heidelberg University", "DE", "Heidelberg", "https://www.uni-heidelberg.de/en/study",
        ["physics", "math", "biology", "medicine", "economics", "social_sciences", "cs"], None, 16000, "none", "2027-07-15", [DE_SCHOOL, DE_LANG], EU_DOCS, 84),
    row("kit", "Karlsruhe Institute of Technology", "DE", "Karlsruhe", "https://www.kit.edu/english/study.php",
        ["engineering", "cs", "physics", "math", "economics"], None, 16000, "none", "2027-07-15", [DE_SCHOOL, DE_LANG], EU_DOCS, 102),
    row("tu_berlin", "Technische Universität Berlin", "DE", "Berlin", "https://www.tu.berlin/en/studying",
        ["engineering", "cs", "math", "physics", "economics", "design"], None, 14000, "none", "2027-07-15", [DE_SCHOOL, DE_LANG], EU_DOCS, 145),
    row("hu_berlin", "Humboldt University of Berlin", "DE", "Berlin", "https://www.hu-berlin.de/en/studies",
        ["economics", "social_sciences", "math", "physics", "biology", "cs"], None, 14000, "none", "2027-07-15", [DE_SCHOOL, DE_LANG], EU_DOCS, 126),
    row("fu_berlin", "Freie Universität Berlin", "DE", "Berlin", "https://www.fu-berlin.de/en/studium",
        ["economics", "business", "social_sciences", "cs", "math", "physics", "biology"], None, 14000, "none", "2027-07-15", [DE_SCHOOL, DE_LANG], EU_DOCS, 97),
    row("freiburg", "University of Freiburg", "DE", "Freiburg", "https://uni-freiburg.de/en/study",
        ["biology", "medicine", "economics", "physics", "math", "cs", "social_sciences"], None, 16000, "none", "2027-07-15", [DE_SCHOOL, DE_LANG], EU_DOCS, 192),
    row("constructor", "Constructor University", "DE", "Bremen", "https://constructor.university/admission-aid",
        ["cs", "engineering", "business", "economics", "math", "physics", "biology", "social_sciences"], 6.5, 36000, "partial", "2027-03-01",
        ["Частный вуз, обучение на английском"], EU_DOCS, UNRANKED),
    # --- South Korea ---------------------------------------------------------
    row("korea_u", "Korea University", "KR", "Seoul", "https://oia.korea.ac.kr/oia/admission/undergraduate.do",
        ["business", "economics", "engineering", "cs", "social_sciences", "biology", "medicine"], 5.5, 16000, "merit_only", "2027-01-15",
        ["Корейский язык (TOPIK) для большинства программ"], ASIA_DOCS, 61),
    row("postech", "POSTECH", "KR", "Pohang", "https://adm-u.postech.ac.kr/eng",
        ["engineering", "cs", "physics", "math", "biology"], 6.0, 13000, "merit_only", "2026-11-01", ["Интервью"], ASIA_DOCS, 98),
    row("skku", "Sungkyunkwan University", "KR", "Seoul / Suwon", "https://admission-global.skku.edu",
        ["business", "economics", "engineering", "cs", "social_sciences", "biology", "design"], 5.5, 16000, "merit_only", "2027-01-15",
        ["Корейский язык (TOPIK) для большинства программ"], ASIA_DOCS, 123),
    row("hanyang", "Hanyang University", "KR", "Seoul", "https://go.hanyang.ac.kr",
        ["engineering", "cs", "business", "economics", "design", "social_sciences"], 5.5, 16000, "merit_only", "2027-01-15",
        ["Корейский язык (TOPIK) для большинства программ"], ASIA_DOCS, 164),
    row("kyunghee", "Kyung Hee University", "KR", "Seoul", "https://iadmission.khu.ac.kr",
        ["business", "social_sciences", "medicine", "design", "cs", "engineering"], 5.5, 15000, "merit_only", "2027-01-15",
        ["Корейский язык (TOPIK) для большинства программ"], ASIA_DOCS, 327),
    row("ewha", "Ewha Womans University", "KR", "Seoul", "https://www.ewha.ac.kr/ewhaen/admission/undergraduate.do",
        ["social_sciences", "business", "design", "biology", "cs", "engineering"], 5.5, 16000, "merit_only", "2027-01-15",
        ["Только для девушек", "Корейский язык (TOPIK) для большинства программ"], ASIA_DOCS, 347),
    row("unist", "UNIST", "KR", "Ulsan", "https://adm-g.unist.ac.kr",
        ["engineering", "cs", "physics", "math", "biology", "business"], 6.0, 12000, "merit_only", "2026-11-15", [], ASIA_DOCS, 300),
    # --- Singapore (6 autonomous universities in total) -----------------------
    row("sutd", "Singapore University of Technology and Design", "SG", "Singapore", "https://www.sutd.edu.sg/admissions/undergraduate",
        ["engineering", "cs", "design", "math"], 6.5, 45000, "partial", "2027-03-15", ["Интервью"], ASIA_DOCS, UNRANKED),
    row("sit", "Singapore Institute of Technology", "SG", "Singapore", "https://www.singaporetech.edu.sg/admissions",
        ["engineering", "cs", "design", "business"], 6.5, 40000, "partial", "2027-03-15", [], ASIA_DOCS, UNRANKED),
    row("suss", "Singapore University of Social Sciences", "SG", "Singapore", "https://www.suss.edu.sg/full-time-undergraduate",
        ["business", "social_sciences", "economics", "cs"], 6.5, 38000, "partial", "2027-03-15", [], ASIA_DOCS, UNRANKED),
    # --- Hong Kong -----------------------------------------------------------
    row("polyu", "The Hong Kong Polytechnic University", "HK", "Hong Kong", "https://www.polyu.edu.hk/study/ug/international",
        ["engineering", "cs", "business", "design", "biology", "social_sciences"], 6.0, 34000, "merit_only", "2027-01-05", [], ASIA_DOCS, 57),
    row("cityu", "City University of Hong Kong", "HK", "Hong Kong", "https://www.cityu.edu.hk/admo",
        ["engineering", "cs", "business", "economics", "social_sciences", "design", "math", "physics"], 6.5, 34000, "merit_only", "2027-01-05", [], ASIA_DOCS, 62),
    row("hkbu", "Hong Kong Baptist University", "HK", "Hong Kong", "https://admissions.hkbu.edu.hk",
        ["business", "social_sciences", "cs", "design", "biology", "math"], 6.0, 30000, "merit_only", "2027-01-05", [], ASIA_DOCS, 252),
    row("lingnan", "Lingnan University", "HK", "Hong Kong", "https://www.ln.edu.hk/admissions/ug",
        ["business", "economics", "social_sciences", "cs"], 6.0, 28000, "merit_only", "2027-01-05", [], ASIA_DOCS, 571),
    row("hkmu", "Hong Kong Metropolitan University", "HK", "Hong Kong", "https://admissions.hkmu.edu.hk",
        ["business", "cs", "social_sciences", "design", "biology"], 6.0, 26000, "merit_only", "2027-01-05", [], ASIA_DOCS, UNRANKED),
    row("hsuhk", "The Hang Seng University of Hong Kong", "HK", "Hong Kong", "https://www.hsu.edu.hk/en/admissions",
        ["business", "economics", "cs", "social_sciences", "design"], 6.0, 26000, "merit_only", "2027-01-05", [], ASIA_DOCS, UNRANKED),
    row("eduhk", "The Education University of Hong Kong", "HK", "Hong Kong", "https://www.eduhk.hk/main/admission",
        ["social_sciences"], 6.0, 26000, "merit_only", "2027-01-05", [], ASIA_DOCS, UNRANKED),
    # --- China ---------------------------------------------------------------
    row("zju", "Zhejiang University", "CN", "Hangzhou", "https://iczu.zju.edu.cn/english",
        ["engineering", "cs", "economics", "business", "medicine", "biology", "math"], 6.0, 12000, "partial", "2027-03-31",
        [CN_LANG], ASIA_DOCS, 47),
    row("sjtu", "Shanghai Jiao Tong University", "CN", "Shanghai", "https://isc.sjtu.edu.cn/EN",
        ["engineering", "cs", "business", "economics", "medicine", "math", "physics"], 6.0, 12000, "partial", "2027-03-15",
        [CN_LANG], ASIA_DOCS, 45),
    row("nju", "Nanjing University", "CN", "Nanjing", "https://hwxy.nju.edu.cn/en",
        ["physics", "math", "cs", "economics", "business", "social_sciences"], 6.0, 11000, "partial", "2027-03-31",
        [CN_LANG], ASIA_DOCS, 138),
    row("nyu_shanghai", "NYU Shanghai", "CN", "Shanghai", "https://shanghai.nyu.edu/admissions",
        ["business", "economics", "cs", "engineering", "math", "physics", "biology", "social_sciences"], 7.5, 85000, "partial",
        [("ED", "2026-11-01"), ("RD", "2027-01-05")], ["Подача через NYU / Common App, эссе"], US_DOCS, UNRANKED),
    row("dku", "Duke Kunshan University", "CN", "Kunshan", "https://undergrad.dukekunshan.edu.cn",
        ["cs", "economics", "biology", "math", "physics", "social_sciences"], 7.0, 75000, "partial",
        [("ED", "2026-11-01"), ("RD", "2027-01-04")], ["Подача через Common App, эссе"], US_DOCS, UNRANKED),
    row("xjtlu", "Xi'an Jiaotong-Liverpool University", "CN", "Suzhou", "https://www.xjtlu.edu.cn/en/admissions/international",
        ["business", "economics", "engineering", "cs", "design", "math", "biology"], 6.0, 22000, "merit_only", "2027-06-30",
        ["Обучение на английском, диплом University of Liverpool"], ASIA_DOCS, UNRANKED),
    row("unnc", "University of Nottingham Ningbo China", "CN", "Ningbo", "https://www.nottingham.edu.cn/en/admissions",
        ["business", "economics", "engineering", "cs", "social_sciences"], 6.5, 22000, "merit_only", "2027-06-30",
        ["Обучение на английском, диплом University of Nottingham"], ASIA_DOCS, UNRANKED),
    # --- Italy ---------------------------------------------------------------
    row("sapienza", "Sapienza University of Rome", "IT", "Rome", "https://www.uniroma1.it/en/pagina/international-students",
        ["engineering", "cs", "economics", "business", "physics", "math", "medicine", "design"], 6.0, 15000, "partial", "2027-04-30",
        ["Предварительная регистрация на Universitaly"], EU_DOCS, 132),
    row("padova", "University of Padua", "IT", "Padua", "https://www.unipd.it/en/admission",
        ["engineering", "economics", "business", "cs", "physics", "math", "biology", "medicine", "social_sciences"], 6.0, 14000, "partial", "2027-03-31",
        ["Предварительная регистрация на Universitaly"], EU_DOCS, 233),
    row("polito", "Politecnico di Torino", "IT", "Turin", "https://www.polito.it/en/education/applying-and-enrolling",
        ["engineering", "cs", "design", "math", "physics"], 6.0, 15000, "partial", "2027-03-31", ["Вступительный тест TIL"], EU_DOCS, 252),
    row("unimi", "University of Milan", "IT", "Milan", "https://www.unimi.it/en/study/bachelor-and-master-study",
        ["economics", "business", "social_sciences", "biology", "medicine", "physics", "math", "cs"], 6.0, 16000, "partial", "2027-04-30",
        ["Предварительная регистрация на Universitaly"], EU_DOCS, 276),
    row("unitn", "University of Trento", "IT", "Trento", "https://www.unitn.it/en/international-students",
        ["economics", "business", "cs", "engineering", "math", "physics", "social_sciences"], 6.0, 13000, "partial", "2027-03-31", [], EU_DOCS, 391),
    row("luiss", "LUISS Guido Carli University", "IT", "Rome", "https://www.luiss.edu/admissions",
        ["economics", "business", "social_sciences"], 6.0, 30000, "merit_only", "2027-04-30", ["Вступительный тест LUISS или SAT"], EU_DOCS, UNRANKED),
    row("pisa", "University of Pisa", "IT", "Pisa", "https://www.unipi.it/index.php/english",
        ["engineering", "cs", "economics", "business", "math", "physics", "biology", "medicine"], 6.0, 13000, "partial", "2027-04-30",
        ["Большинство бакалаврских программ на итальянском"], EU_DOCS, 400),
    # --- Japan ---------------------------------------------------------------
    row("keio", "Keio University (PEARL / GIGA)", "JP", "Tokyo", "https://admissions.keio.ac.jp/en",
        ["economics", "business", "social_sciences", "cs"], 6.5, 22000, "merit_only", "2026-12-01", [], ASIA_DOCS, 196),
    row("osaka", "Osaka University (English-taught programmes)", "JP", "Osaka", "https://www.osaka-u.ac.jp/en/admissions/faculty",
        ["engineering", "biology", "social_sciences", "physics"], 6.0, 15000, "merit_only", "2026-12-01", [], ASIA_DOCS, 86),
    row("tohoku", "Tohoku University (FGL)", "JP", "Sendai", "https://www.insc.tohoku.ac.jp/english/admission",
        ["engineering", "physics", "biology", "math", "cs"], 6.0, 15000, "merit_only", "2026-12-01", [], ASIA_DOCS, 107),
    row("nagoya", "Nagoya University (G30)", "JP", "Nagoya", "https://admissions.g30.nagoya-u.ac.jp",
        ["engineering", "physics", "biology", "economics", "business", "social_sciences"], 6.0, 15000, "merit_only", "2026-12-01", [], ASIA_DOCS, 152),
    row("sophia", "Sophia University (English-taught programmes)", "JP", "Tokyo", "https://adm.sophia.ac.jp/eng",
        ["economics", "business", "social_sciences", "engineering"], 6.0, 22000, "merit_only", "2027-01-15", [], ASIA_DOCS, UNRANKED),
    row("icu", "International Christian University", "JP", "Tokyo", "https://www.icu.ac.jp/en/admissions",
        ["economics", "business", "social_sciences", "math", "physics", "biology", "cs"], 6.5, 24000, "merit_only", "2027-01-15",
        ["Первый год — японский язык (для поступающих на английском)"], ASIA_DOCS, UNRANKED),
    row("apu", "Ritsumeikan Asia Pacific University", "JP", "Beppu", "https://admissions.apu.ac.jp",
        ["business", "economics", "social_sciences", "cs"], 5.5, 20000, "merit_only", "2026-12-01", [], ASIA_DOCS, UNRANKED),
    # --- Switzerland ---------------------------------------------------------
    row("unisg", "University of St. Gallen", "CH", "St. Gallen", "https://www.unisg.ch/en/studium/bachelor",
        ["business", "economics", "social_sciences", "cs"], None, 35000, "merit_only", "2027-04-30",
        ["Вступительный экзамен для иностранцев", "Первый курс на английском, дальше в основном на немецком"], EU_DOCS, UNRANKED),
    row("unige", "University of Geneva", "CH", "Geneva", "https://www.unige.ch/admissions/en",
        ["economics", "business", "social_sciences", "physics", "math", "biology", "medicine", "cs"], None, 30000, "none", "2027-02-28",
        ["Обучение на французском (B2)"], EU_DOCS, 113),
    row("unil", "University of Lausanne", "CH", "Lausanne", "https://www.unil.ch/immat/en/home.html",
        ["economics", "business", "social_sciences", "biology", "medicine"], None, 30000, "none", "2027-02-28",
        ["Обучение на французском (B2)"], EU_DOCS, 219),
    row("unibas", "University of Basel", "CH", "Basel", "https://www.unibas.ch/en/Studies.html",
        ["biology", "medicine", "economics", "physics", "math", "cs", "social_sciences"], None, 30000, "none", "2027-04-30",
        ["Обучение на немецком (C1)"], EU_DOCS, 128),
    row("unibe", "University of Bern", "CH", "Bern", "https://www.unibe.ch/studies/index_eng.html",
        ["biology", "medicine", "economics", "business", "physics", "math", "cs", "social_sciences"], None, 30000, "none", "2027-04-30",
        ["Обучение на немецком (C1)"], EU_DOCS, 119),
    row("usi", "Università della Svizzera italiana", "CH", "Lugano", "https://www.usi.ch/en/education/bachelor",
        ["economics", "business", "cs", "design", "social_sciences"], 6.5, 30000, "merit_only", "2027-04-30",
        ["Часть программ на итальянском"], EU_DOCS, UNRANKED),
    row("franklin", "Franklin University Switzerland", "CH", "Lugano", "https://www.fus.edu/admissions",
        ["business", "economics", "social_sciences"], 6.5, 65000, "partial", "2027-03-01", ["Частный вуз американского типа"], US_DOCS, UNRANKED),
    # --- France --------------------------------------------------------------
    row("paris_saclay", "Université Paris-Saclay", "FR", "Orsay", "https://www.universite-paris-saclay.fr/en/admission",
        ["physics", "math", "cs", "biology", "engineering", "economics"], None, 17000, "partial", "2026-12-15", [FR_LANG], EU_DOCS, 70),
    row("psl", "PSL University", "FR", "Paris", "https://psl.eu/en/education",
        ["physics", "math", "cs", "economics", "social_sciences", "biology"], None, 17000, "partial", "2027-03-15", [FR_LANG], EU_DOCS, 24),
    row("paris_cite", "Université Paris Cité", "FR", "Paris", "https://u-paris.fr/en/international-students",
        ["medicine", "biology", "physics", "math", "cs", "social_sciences", "economics"], None, 17000, "partial", "2026-12-15", [FR_LANG], EU_DOCS, 236),
    row("grenoble", "Université Grenoble Alpes", "FR", "Grenoble", "https://www.univ-grenoble-alpes.fr/education/admission",
        ["physics", "math", "cs", "engineering", "economics", "biology", "social_sciences"], None, 15000, "partial", "2026-12-15", [FR_LANG], EU_DOCS, 294),
    row("essec", "ESSEC Business School (Global BBA)", "FR", "Cergy", "https://www.essec.edu/en/program/global-bba/",
        ["business", "economics"], 6.5, 40000, "partial", "2027-03-15", ["Интервью"], EU_DOCS, UNRANKED),
    row("escp", "ESCP Business School (Bachelor in Management)", "FR", "Paris", "https://escp.eu/programmes/bachelor-in-management",
        ["business", "economics"], 6.5, 40000, "merit_only", "2027-03-15", ["Интервью", "Обучение в 3 странах"], EU_DOCS, UNRANKED),
    row("aup", "The American University of Paris", "FR", "Paris", "https://www.aup.edu/admissions",
        ["business", "economics", "cs", "social_sciences", "design"], 6.5, 55000, "partial", "2027-02-01", ["Частный вуз американского типа"], US_DOCS, UNRANKED),
    # --- Australia -----------------------------------------------------------
    row("monash", "Monash University", "AU", "Melbourne", "https://www.monash.edu/study/international",
        ["engineering", "cs", "economics", "business", "medicine", "biology", "design", "social_sciences", "math", "physics"], 6.5, 55000, "merit_only",
        "2026-11-30", [FOUNDATION], UK_DOCS, 37),
    row("uq", "The University of Queensland", "AU", "Brisbane", "https://study.uq.edu.au/admissions",
        ["engineering", "cs", "economics", "business", "medicine", "biology", "social_sciences", "math", "physics"], 6.5, 55000, "merit_only",
        "2026-11-30", [FOUNDATION], UK_DOCS, 40),
    row("uwa", "The University of Western Australia", "AU", "Perth", "https://www.uwa.edu.au/study/how-to-apply",
        ["engineering", "cs", "economics", "business", "biology", "math", "physics", "social_sciences"], 6.5, 50000, "merit_only",
        "2026-11-30", [FOUNDATION], UK_DOCS, 77),
    row("uts", "University of Technology Sydney", "AU", "Sydney", "https://www.uts.edu.au/study/international",
        ["engineering", "cs", "business", "design", "economics", "social_sciences"], 6.5, 52000, "merit_only",
        "2026-11-30", [FOUNDATION], UK_DOCS, 88),
    row("macquarie", "Macquarie University", "AU", "Sydney", "https://www.mq.edu.au/study/international-students",
        ["business", "economics", "cs", "engineering", "social_sciences", "biology"], 6.5, 50000, "merit_only",
        "2026-11-30", [FOUNDATION], UK_DOCS, 130),
    row("rmit", "RMIT University", "AU", "Melbourne", "https://www.rmit.edu.au/study-with-us/international-students",
        ["design", "engineering", "cs", "business", "social_sciences"], 6.5, 48000, "merit_only",
        "2026-11-30", [FOUNDATION], UK_DOCS, 123),
    # --- Ireland -------------------------------------------------------------
    row("ucc", "University College Cork", "IE", "Cork", "https://www.ucc.ie/en/international",
        ["business", "economics", "cs", "engineering", "medicine", "biology", "social_sciences"], 6.5, 40000, "merit_only", "2027-06-30",
        ["Foundation year или 1 год вуза в РК для аттестата"], UK_DOCS, 273),
    row("dcu", "Dublin City University", "IE", "Dublin", "https://www.dcu.ie/international",
        ["business", "cs", "engineering", "social_sciences", "economics"], 6.5, 38000, "merit_only", "2027-06-30",
        ["Foundation year или 1 год вуза в РК для аттестата"], UK_DOCS, 436),
    row("maynooth", "Maynooth University", "IE", "Maynooth", "https://www.maynoothuniversity.ie/international",
        ["cs", "math", "physics", "business", "economics", "social_sciences", "biology"], 6.5, 35000, "merit_only", "2027-06-30",
        ["Foundation year или 1 год вуза в РК для аттестата"], UK_DOCS, 801),
    row("ul", "University of Limerick", "IE", "Limerick", "https://www.ul.ie/international",
        ["engineering", "cs", "business", "design", "social_sciences"], 6.5, 36000, "merit_only", "2027-06-30",
        ["Foundation year или 1 год вуза в РК для аттестата"], UK_DOCS, 421),
    row("tu_dublin", "Technological University Dublin", "IE", "Dublin", "https://www.tudublin.ie/study/international-students",
        ["engineering", "cs", "business", "design"], 6.0, 34000, "merit_only", "2027-06-30",
        ["Foundation year или 1 год вуза в РК для аттестата"], UK_DOCS, 851),
    row("rcsi", "RCSI University of Medicine and Health Sciences", "IE", "Dublin", "https://www.rcsi.com/dublin/undergraduate",
        ["medicine", "biology"], 6.5, 75000, "merit_only", "2027-02-01", ["Интервью / тест для медицины"], UK_DOCS, UNRANKED),
    row("mtu", "Munster Technological University", "IE", "Cork", "https://www.mtu.ie/international",
        ["engineering", "cs", "business", "design"], 6.0, 30000, "merit_only", "2027-06-30",
        ["Foundation year или 1 год вуза в РК для аттестата"], UK_DOCS, UNRANKED),
    # --- Sweden (few English-taught bachelor's programmes) ---------------------
    row("sse", "Stockholm School of Economics", "SE", "Stockholm", "https://www.hhs.se/en/education/bsc",
        ["business", "economics"], 6.5, 35000, "merit_only", "2027-01-15", ["Английский уровня English 6 / IELTS"], EU_DOCS, UNRANKED),
    row("jonkoping", "Jönköping University", "SE", "Jönköping", "https://ju.se/en/study-at-ju.html",
        ["business", "economics", "engineering", "cs", "design", "social_sciences"], 6.5, 25000, "merit_only", "2027-01-15",
        ["1 год вуза в РК для аттестата"], EU_DOCS, UNRANKED),
    row("linnaeus", "Linnaeus University", "SE", "Växjö / Kalmar", "https://lnu.se/en/education/",
        ["business", "cs", "social_sciences", "design"], 6.5, 24000, "merit_only", "2027-01-15",
        ["1 год вуза в РК для аттестата"], EU_DOCS, UNRANKED),
    row("stockholm_u", "Stockholm University", "SE", "Stockholm", "https://www.su.se/english/education",
        ["social_sciences", "economics", "business", "math", "physics", "biology", "cs"], 6.5, 26000, "merit_only", "2027-01-15",
        ["Мало англоязычных бакалаврских программ", "1 год вуза в РК для аттестата"], EU_DOCS, 118),
    row("gothenburg", "University of Gothenburg", "SE", "Gothenburg", "https://www.gu.se/en/study-in-gothenburg",
        ["social_sciences", "economics", "business", "biology", "cs", "design"], 6.5, 26000, "merit_only", "2027-01-15",
        ["Мало англоязычных бакалаврских программ", "1 год вуза в РК для аттестата"], EU_DOCS, 187),
    row("chalmers", "Chalmers University of Technology", "SE", "Gothenburg", "https://www.chalmers.se/en/education/find-programmes/",
        ["engineering", "cs", "physics", "math", "design"], 6.5, 28000, "merit_only", "2027-01-15",
        ["Мало англоязычных бакалаврских программ", "1 год вуза в РК для аттестата"], EU_DOCS, 129),
    row("linkoping", "Linköping University", "SE", "Linköping", "https://liu.se/en/education",
        ["engineering", "cs", "business", "economics", "social_sciences"], 6.5, 26000, "merit_only", "2027-01-15",
        ["Мало англоязычных бакалаврских программ", "1 год вуза в РК для аттестата"], EU_DOCS, 285),
    # --- Spain ---------------------------------------------------------------
    row("upf", "Pompeu Fabra University", "ES", "Barcelona", "https://www.upf.edu/web/international",
        ["economics", "business", "social_sciences", "cs", "engineering", "biology"], 6.5, 18000, "none", "2027-06-30",
        [ES_HOMOLOG], EU_DOCS, 245),
    row("uab", "Autonomous University of Barcelona", "ES", "Barcelona", "https://www.uab.cat/web/study-abroad-1345663011069.html",
        ["economics", "business", "social_sciences", "cs", "engineering", "biology", "physics", "math", "medicine"], None, 17000, "none", "2027-06-30",
        ["Обучение на испанском/каталанском (B2)", ES_HOMOLOG], EU_DOCS, 164),
    row("uam", "Autonomous University of Madrid", "ES", "Madrid", "https://www.uam.es/uam/en/estudios/grado",
        ["economics", "business", "social_sciences", "cs", "physics", "math", "biology", "medicine"], None, 17000, "none", "2027-06-30",
        ["Обучение на испанском (B2)", ES_HOMOLOG], EU_DOCS, 199),
    row("ucm", "Complutense University of Madrid", "ES", "Madrid", "https://www.ucm.es/english",
        ["economics", "business", "social_sciences", "cs", "physics", "math", "biology", "medicine", "design"], None, 17000, "none", "2027-06-30",
        ["Обучение на испанском (B2)", ES_HOMOLOG], EU_DOCS, 184),
    row("esade", "ESADE (Ramon Llull University)", "ES", "Barcelona", "https://www.esade.edu/en/programmes/bachelor",
        ["business", "economics", "social_sciences"], 6.5, 40000, "merit_only", "2027-03-15", ["Вступительный тест и интервью"], EU_DOCS, UNRANKED),
    row("unav", "University of Navarra", "ES", "Pamplona", "https://www.unav.edu/en/admission",
        ["medicine", "business", "economics", "social_sciences", "design", "biology"], None, 30000, "merit_only", "2027-04-30",
        ["Большинство программ на испанском"], EU_DOCS, 250),
    row("upc", "Universitat Politècnica de Catalunya", "ES", "Barcelona", "https://www.upc.edu/en/bachelors",
        ["engineering", "cs", "design", "math", "physics"], None, 17000, "none", "2027-06-30",
        ["Обучение на испанском/каталанском (B2)", ES_HOMOLOG], EU_DOCS, 339),
    # --- Canada --------------------------------------------------------------
    row("mcmaster", "McMaster University", "CA", "Hamilton", "https://future.mcmaster.ca/admission/international/",
        ["engineering", "cs", "business", "economics", "biology", "math", "physics", "social_sciences"], 6.5, 55000, "merit_only", "2027-01-15",
        ["Supplementary application на части программ"], ["transcript", "passport"], 176),
    row("ualberta", "University of Alberta", "CA", "Edmonton", "https://www.ualberta.ca/en/admissions/international/index.html",
        ["engineering", "cs", "business", "economics", "biology", "math", "physics", "social_sciences"], 6.5, 50000, "merit_only", "2027-03-01",
        [], ["transcript", "passport"], 96),
    row("queens", "Queen's University", "CA", "Kingston", "https://www.queensu.ca/admission/international-students",
        ["engineering", "cs", "business", "economics", "biology", "math", "physics", "social_sciences"], 6.5, 58000, "merit_only", "2027-01-15",
        ["Personal Statement of Experience (PSE)"], ["transcript", "essay", "passport"], 193),
    row("western", "Western University", "CA", "London, ON", "https://welcome.uwo.ca/admissions/international-students/",
        ["engineering", "cs", "business", "economics", "biology", "math", "physics", "social_sciences"], 6.5, 55000, "merit_only", "2027-02-01",
        [], ["transcript", "passport"], 120),
    row("uottawa", "University of Ottawa", "CA", "Ottawa", "https://www.uottawa.ca/study/undergraduate-studies/international-students",
        ["engineering", "cs", "business", "economics", "biology", "math", "physics", "social_sciences"], 6.5, 50000, "merit_only", "2027-04-01",
        ["Часть программ на французском"], ["transcript", "passport"], 189),
    row("ucalgary", "University of Calgary", "CA", "Calgary", "https://www.ucalgary.ca/future-students/undergraduate/international",
        ["engineering", "cs", "business", "economics", "biology", "math", "physics", "design", "social_sciences"], 6.5, 50000, "merit_only", "2027-03-01",
        [], ["transcript", "passport"], 182),
]


def sourced(value, url):
    return {"value": value, "source_url": url, "checked_at": None, "evidence": None, "is_demo": True}


def build():
    universities = []
    for (uid, name, country, city, site, majors, rate, sat, gpa, ielts, cost, aid, deadlines, extra, docs, rank) in ROWS:
        universities.append({
            "id": uid, "name": name, "country": country, "city": city, "website": site, "majors": majors,
            "acceptance_rate": sourced(rate, site),
            "sat": sourced({"p25": sat[0], "p50": None, "p75": sat[1]} if sat else None, site),
            "gpa_avg": sourced(gpa, site),
            "ielts_min": sourced(ielts, site),
            "cost_per_year_usd": sourced(cost, site),
            "intl_aid": sourced(aid, site),
            "deadlines": [sourced({"type": t, "date": d}, site) for t, d in deadlines],
            "extra_requirements": extra,
            "documents": docs,
            "world_rank": rank,
        })
    # Rows that already contain pipeline-verified facts (is_demo=false) are owned by pipeline/verify.py: keep them.
    existing_path = HERE / "universities.json"
    if existing_path.exists():
        existing = {u["id"]: u for u in json.loads(existing_path.read_text(encoding="utf-8"))}
        def has_real(u: dict) -> bool:
            facts = [u[f] for f in ("acceptance_rate", "sat", "gpa_avg", "ielts_min", "cost_per_year_usd", "intl_aid")]
            return any(not f.get("is_demo", True) for f in facts + u["deadlines"])
        universities = [existing[u["id"]] if u["id"] in existing and has_real(existing[u["id"]]) else u
                        for u in universities]
    majors = [{"id": i, "name_ru": ru, "name_en": en, "cip_codes": cip} for i, ru, en, cip in MAJORS]
    (HERE / "universities.json").write_text(json.dumps(universities, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (HERE / "majors.json").write_text(json.dumps(majors, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"universities: {len(universities)}, majors: {len(majors)}")


if __name__ == "__main__":
    build()
